name: AmazonLinux2 Wheel Tester
on:
  push:
    branches:
      - master
      - fix-for-bcrypt
  schedule:
    # Run nightly
    - cron: '0 0 * * *'

jobs:
  al2_test:
    runs-on: [self-hosted, linux, ARM64, al2]
    container: amazonlinux:2
    strategy:
      fail-fast: false
      matrix:
        WHEEL:
          - PIP_NAME: numpy
            PKG_TEST: import numpy
          - PIP_NAME: bcrypt
            PKG_TEST: import bcrypt
          - PIP_NAME: pymongo
            PKG_TEST: |
              import pymongo
              import pymongo.message
          - PIP_NAME: lxml
            PKG_TEST: |
              import lxml._elementpath
              import lxml.builder
              import lxml.objectify
              import lxml.etree
              import lxml.sax
          - PIP_NAME: lazy-object-proxy
            PKG_TEST: import lazy_object_proxy
          - PIP_NAME: simplejson
            PKG_TEST: |
              import simplejson
              simplejson._speedups
          - PIP_NAME: Pillow
            PKG_TEST: |
              import PIL
              import PIL._imagingcms
              import PIL._imaging
              import PIL._imagingft
              import PIL._imagingmath
              import PIL._imagingmorph
              import PIL._imagingtk
          - PIP_NAME: kiwisolver
            PKG_TEST: import kiwisolver
    name: "Amazon Linux 2 for ${{ matrix.WHEEL.PIP_NAME }}"
    steps:
      - run: yum install -y python3-pip
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install ${{ matrix.WHEEL.PIP_NAME }}
      - run: echo "${{ matrix.WHEEL.PKG_TEST }}" | python3
